### ISSUE TITLE
fetch from local directory

### ISSUE THREAD

**Issue by TowelSniffer** [chanind/hanzi-writer-data-jp#1]
I am using this to make Anki flashcards cards and it's excellent but I would like for it to work offline so that I can always do my reviews. the problem is with:

HanziWriter.create('target-div', '私', {

  width: 400,

  height: 400,

  charDataLoader: (char, onLoad, onError) => {

    fetch(`https://cdn.jsdelivr.net/npm/hanzi-writer-data-jp@0/${char}.json`)

      .then(res => res.json())

      .then(onLoad)

      .catch(onError);

  }

})

fetch does not work with local files (actually, it does on Anki desktop but not on ankidroid for mobile). Is there an alternative way to load the json file?

**Comment by chanind** [comment]
You can load the JSON file from the local file system or just directly hardcode the character in the loader function, whichever works. Just call `onLoad` with the results of the json, and you should be good to go. For example:

```js
charDataLoader: async (char, onLoad, onError) => {
  const charJson = await getCharDataSomehow(char);
  onLoad(charJson);
}
```

**Comment by TowelSniffer** [comment]
alright, thanks for your help

**Comment by krmanik** [comment]
Check this, if needed,
https://github.com/ankidroid/Anki-Android/issues/5412#issuecomment-638897351
