### ISSUE TITLE
Character 社

### ISSUE THREAD

**Issue by JhonnySalles** [chanind/hanzi-writer-data-jp#2]
The character 社 resulting another character. I believe there is an error in it.

![image](https://user-images.githubusercontent.com/43912638/85164870-578e9c80-b23b-11ea-8a69-8e28502d6376.png)

I would also like to know the possibility of increasing kanji by adding Chinese and radicals. If you know and do not want to do, I would like a tip on how to generate the coordinates, if it was extracted from a svg or something similar, as I can try to work on the characters for improvement.

**Comment by chanind** [comment]
That does look messed up, I'll investigate further. As far as generating your own Kanji, I'm actually not sure how this works. The data here is from https://github.com/parsimonhi/animCJK. If you ask in that repo they may be able to give you some guidance on how to generate your own custom characters.

**Comment by JhonnySalles** [comment]
I'll be checking the link.

Of several kanji that I tested (I am studying on a deck), so far the one above was the only one with a problem, the rest seems to be correct.

**Comment by cyrille-polymtl** [comment]
I found the same problem in an anki deck using those data.
When I look in the repo, it seems that the all json file has a correct formula for 社,
but not the 社 json file.

Can you correct it please ?

Thanks.

**Comment by chanind** [comment]
I think this has something bizarre to do with case-insensitive file systems on macs. For some reason when I try to run the import script on my mac it messes up the filenames of a few characters, but on linux it doesn't. Sorry about that! Hopefully it's fixed now in 0.0.2. If not, let me know and I'll keep digging in!
